###### uncomment the code below, you can use the latest verse
# I fixed this image to use 4.3.1
# https://hub.docker.com/layers/rocker/rstudio/4.3.1/images/sha256-91f68963b3fa85628b55acebb6783b42ae865bb5c967f9f0ca435c16e5a3d762?context=explore
# docker pull rocker/rstudio:4.3.1
# ARG BASE_CONTAINER=rocker/rstudio:4.3.1
# FROM $BASE_CONTAINER
FROM --platform=linux/amd64 rocker/rstudio:4.3.1

# install lib dependencies for tidyverse
RUN apt-get update && apt-get install -y \
    libfontconfig1-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfribidi-dev \ 
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    cmake

# install r packages from tsinghua's mirror: https://mirrors.tuna.tsinghua.edu.cn/CRAN/
# you may also use other mirrors: https://cran.r-project.org/mirrors.html

RUN R -e "install.packages('pacman', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('here', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('devtools', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('tidyverse', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('data.table', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('psych', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('car', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
# reinstall Matrix to the 1.6.5, instead of latest version that requires R 4.4
RUN R -e "remove.packages('Matrix', lib='/usr/local/lib/R/library')"
RUN R -e "devtools::install_version('Matrix', version = '1.6.5', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages(c('CTT','ltm', 'mirt', 'lordif'), repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages(c('lavaan','semPlot','semTools'), repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages(c('foreach', 'parallel', 'iterators', 'doParallel','cluster'), repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('gplots', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
RUN R -e "install.packages('RcppProgress', repos = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"

# install r package from github
RUN R -e "devtools::install_github('linxihui/NNLM@65303c99d1059ca90cdbabeaf872521717037255')"

# add data
# COPY /example/Script_example.Rmd /home/rstudio/example/
# COPY /example/Script_example.r /home/rstudio/example/
# COPY /example/df_example.csv /home/rstudio/example/
